##02-01 파이토치 패키지의 기본 구성

1. torch
메인 네임스페이스입니다. 텐서 등의 다양한 수학 함수가 포함되어져 있으며 Numpy와 유사한 구조를 가집니다.

2. torch.autograd
자동 미분을 위한 함수들이 포함되어져 있습니다. 자동 미분의 on/off를 제어하는 콘텍스트 매니저(enable_grad/no_grad)나 자체 미분 가능 함수를 정의할 때 사용하는 기반 클래스인 'Function' 등이 포함되어져 있습니다.

3. torch.nn
신경망을 구축하기 위한 다양한 데이터 구조나 레이어 등이 정의되어져 있습니다. 예를 들어 RNN, LSTM과 같은 레이어, ReLU와 같은 활성화 함수, MSELoss와 같은 손실 함수들이 있습니다.

4. torch.optim
확률적 경사 하강법(Stochastic Gradient Descent, SGD)를 중심으로 한 파라미터 최적화 알고리즘이 구현되어져 있습니다.

5. torch.utils.data
SGD의 반복 연산을 실행할 때 사용하는 미니 배치용 유틸리티 함수가 포함되어져 있습니다.

6. torch.onnx
ONNX(Open Neural Network Exchange)의 포맷으로 모델을 익스포트(export)할 때 사용합니다. ONNX는 서로 다른 딥 러닝 프레임워크 간에 모델을 공유할 때 사용하는 포맷입니다.


## 02-02 Tensor Manipulation

### 1. 벡터, 행렬 그리고 텐서

#### 1) 벡터, 행렬, 텐서 그림으로 이해하기

- 1차원으로 구성되면, Vector 벡터 : [3, 5, 7]
- 2차원으로 구성되면, Matrix 행렬 : 우리가 아는 그 행렬
- 3차원으로 구성되면, Tensor 텐서 : 그 행렬이 여러 개

#### 2) Pytorch Tensor Shape Convention



##### 2D Tensor (Typical Simple Setting)

2차원 텐서 |t| = (Batch size, dim)

- 행의 크기 -> batch size,
- 열의 크기 -> dim

정확히는 batch size는 행의 크기와 연관되어 있다.
덩어리로 처리할 때, 행 단위로 끊어서 처리하는데, 이 크기 단위를 batch size라고 하는것이다.


##### 3D Tensor(CV)

|t| = (batch size, width, height)

##### 3D Tensor(NLP)

|t| = (batch size, length, dim)

##### NLP 분야의 3D 텐서 예제로 이해하기

아래와 같이 4개의 문장으로 구성된 전체 훈련 데이터가 있습니다.
<br>
[[나는 사과를 좋아해], [나는 바나나를 좋아해], [나는 사과를 싫어해], [나는 바나나를 싫어해]]<br><br>
컴퓨터는 아직 이 상태로는 '나는 사과를 좋아해'가 단어가 1개인지 3개인지 이해하지 못합니다. 우선 컴퓨터의 입력으로 사용하기 위해서는 단어별로 나눠주어야 합니다.<br><br>

[['나는', '사과를', '좋아해'], ['나는', '바나나를', '좋아해'], ['나는', '사과를', '싫어해'], ['나는', '바나나를', '싫어해']]<br><br>
이제 훈련 데이터의 크기는 4 × 3의 크기를 가지는 2D 텐서입니다. 컴퓨터는 텍스트보다는 숫자를 더 잘 처리할 수 있습니데. 이제 각 단어를 벡터로 만들겁니다. 아래와 같이 단어를 3차원의 벡터로 변환했다고 하겠습니다.<br><br>

'나는' = [0.1, 0.2, 0.9]
'사과를' = [0.3, 0.5, 0.1]
'바나나를' = [0.3, 0.5, 0.2]
'좋아해' = [0.7, 0.6, 0.5]
'싫어해' = [0.5, 0.6, 0.7]
<br><br>위 기준을 따라서 훈련 데이터를 재구성하면 아래와 같습니다.<br><br>

[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]
<br><br>이제 훈련 데이터는 4 × 3 × 3의 크기를 가지는 3D 텐서입니다. 이제 batch size를 2로 해보겠습니다.<br><br>

첫번째 배치 #1
[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]]

두번째 배치 #2
[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]
<br><br>컴퓨터는 배치 단위로 가져가서 연산을 수행합니다. 그리고 현재 각 배치의 텐서의 크기는 (2 × 3 × 3)입니다. 이는 (batch size, 문장 길이, 단어 벡터의 차원)의 크기입니다.

### 2. Numpy로 Tensor 만들기

#### 1) 1D with Numpy

In [ ]:
import numpy as np

In [ ]:
t = np.arange(7)
t

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


#### 1-1) Numpy 기초 이해하기 - Pass

#### 2) 2D with Numpy

In [ ]:
t = np.array([[i,i+1,i+2] for i in range(1,11,3)])
t

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

t.ndim이 2차원인 이유는, 현재 행렬이기 때문이다.

In [ ]:
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

Rank of t: 2
Shape of t: (4, 3)


### 3. 파이토치 텐서 선언하기 Pytorch Tensor Allocation

In [2]:
import torch

#### 1) 1D with PyTorch

In [3]:
t = torch.arange(7)
t

tensor([0, 1, 2, 3, 4, 5, 6])

In [4]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [5]:
print(t[0],t[1],t[-1])
print(t[2:5], t[4:-1])
print(t[:2],t[3:])

tensor(0) tensor(1) tensor(6)
tensor([2, 3, 4]) tensor([4, 5])
tensor([0, 1]) tensor([3, 4, 5, 6])


#### 2) 2D with PyTorch

In [7]:
t = torch.tensor([[i,i+1,i+2] for i in range(1,11,3)])
t

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [8]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [9]:
# 첫 번째 차원을 전체 선택,
# 두 번째 차원의 1번째만
print(t[:,1].size())

tensor([ 2,  5,  8, 11])
torch.Size([4])


In [10]:
# 첫 번째 차원을 전체 선택,
# 두 번째 차원은 맨 마지막에서 첫 번째를 제외하고 전부
t[:,:-1]

tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])

#### 3) 브로드캐스팅

자동으로 크기를 맞춰서 연산을 수행하게 한다.

In [11]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [12]:
# Vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) #  [3] -> [3,3]

print(m1 + m2)

tensor([[4., 5.]])


In [13]:
# 2 * 1 Vector + 1 * 2 Vector
m1 = torch.FloatTensor([[1,2]]) # 크기 (1,2)
m2 = torch.FloatTensor([[3],
                        [4]])   # 크기 (2,1)
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


#### 4) 자주 사용되는 기능



##### 1) 행렬 곱셈과 곱셈의 차이
행렬 곱셈과 원소별 곱셈 방식이 있다.