## 02-01 파이토치 패키지의 기본 구성

1. torch
메인 네임스페이스입니다. 텐서 등의 다양한 수학 함수가 포함되어져 있으며 Numpy와 유사한 구조를 가집니다.

2. torch.autograd
자동 미분을 위한 함수들이 포함되어져 있습니다. 자동 미분의 on/off를 제어하는 콘텍스트 매니저(enable_grad/no_grad)나 자체 미분 가능 함수를 정의할 때 사용하는 기반 클래스인 'Function' 등이 포함되어져 있습니다.

3. torch.nn
신경망을 구축하기 위한 다양한 데이터 구조나 레이어 등이 정의되어져 있습니다. 예를 들어 RNN, LSTM과 같은 레이어, ReLU와 같은 활성화 함수, MSELoss와 같은 손실 함수들이 있습니다.

4. torch.optim
확률적 경사 하강법(Stochastic Gradient Descent, SGD)를 중심으로 한 파라미터 최적화 알고리즘이 구현되어져 있습니다.

5. torch.utils.data
SGD의 반복 연산을 실행할 때 사용하는 미니 배치용 유틸리티 함수가 포함되어져 있습니다.

6. torch.onnx
ONNX(Open Neural Network Exchange)의 포맷으로 모델을 익스포트(export)할 때 사용합니다. ONNX는 서로 다른 딥 러닝 프레임워크 간에 모델을 공유할 때 사용하는 포맷입니다.


## 02-02 Tensor Manipulation

### 1. 벡터, 행렬 그리고 텐서

#### 1) 벡터, 행렬, 텐서 그림으로 이해하기

이 때의 차원 => Rank이다.

- 1차원으로 구성되면, Vector 벡터 : [3, 5, 7]
- 2차원으로 구성되면, Matrix 행렬 : 우리가 아는 그 행렬
- 3차원으로 구성되면, Tensor 텐서 : 그 행렬이 여러 개

#### 2) Pytorch Tensor Shape Convention



##### 2D Tensor (Typical Simple Setting)

2차원 텐서 |t| = (Batch size, dim)

- 행의 크기 -> batch size,
- 열의 크기 -> dim

정확히는 batch size는 행의 크기와 연관되어 있다.
덩어리로 처리할 때, 행 단위로 끊어서 처리하는데, 이 크기 단위를 batch size라고 하는것이다.


##### 3D Tensor(CV)

|t| = (batch size, width, height)

##### 3D Tensor(NLP)

|t| = (batch size, length, dim)

##### NLP 분야의 3D 텐서 예제로 이해하기

아래와 같이 4개의 문장으로 구성된 전체 훈련 데이터가 있습니다.
<br>
[[나는 사과를 좋아해], [나는 바나나를 좋아해], [나는 사과를 싫어해], [나는 바나나를 싫어해]]<br><br>
컴퓨터는 아직 이 상태로는 '나는 사과를 좋아해'가 단어가 1개인지 3개인지 이해하지 못합니다. 우선 컴퓨터의 입력으로 사용하기 위해서는 단어별로 나눠주어야 합니다.<br><br>

[['나는', '사과를', '좋아해'], ['나는', '바나나를', '좋아해'], ['나는', '사과를', '싫어해'], ['나는', '바나나를', '싫어해']]<br><br>
이제 훈련 데이터의 크기는 4 × 3의 크기를 가지는 2D 텐서입니다. 컴퓨터는 텍스트보다는 숫자를 더 잘 처리할 수 있습니데. 이제 각 단어를 벡터로 만들겁니다. 아래와 같이 단어를 3차원의 벡터로 변환했다고 하겠습니다.<br><br>

'나는' = [0.1, 0.2, 0.9]
'사과를' = [0.3, 0.5, 0.1]
'바나나를' = [0.3, 0.5, 0.2]
'좋아해' = [0.7, 0.6, 0.5]
'싫어해' = [0.5, 0.6, 0.7]
<br><br>위 기준을 따라서 훈련 데이터를 재구성하면 아래와 같습니다.<br><br>

[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]
<br><br>이제 훈련 데이터는 4 × 3 × 3의 크기를 가지는 3D 텐서입니다. 이제 batch size를 2로 해보겠습니다.<br><br>

첫번째 배치 #1
[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.7, 0.6, 0.5]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.7, 0.6, 0.5]]]

두번째 배치 #2
[[[0.1, 0.2, 0.9], [0.3, 0.5, 0.1], [0.5, 0.6, 0.7]],
 [[0.1, 0.2, 0.9], [0.3, 0.5, 0.2], [0.5, 0.6, 0.7]]]
<br><br>컴퓨터는 배치 단위로 가져가서 연산을 수행합니다. 그리고 현재 각 배치의 텐서의 크기는 (2 × 3 × 3)입니다. 이는 (batch size, 문장 길이, 단어 벡터의 차원)의 크기입니다.

### 2. Numpy로 Tensor 만들기

#### 1) 1D with Numpy

In [ ]:
import numpy as np

In [ ]:
t = np.arange(7)
t

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


#### 1-1) Numpy 기초 이해하기 - Pass

#### 2) 2D with Numpy

In [ ]:
t = np.array([[i,i+1,i+2] for i in range(1,11,3)])
t

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

t.ndim이 2차원인 이유는, 현재 행렬이기 때문이다.

In [ ]:
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

Rank of t: 2
Shape of t: (4, 3)


### 3. 파이토치 텐서 선언하기 Pytorch Tensor Allocation

In [2]:
import torch

#### 1) 1D with PyTorch

In [3]:
t = torch.arange(7)
t

tensor([0, 1, 2, 3, 4, 5, 6])

In [4]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [5]:
print(t[0],t[1],t[-1])
print(t[2:5], t[4:-1])
print(t[:2],t[3:])

tensor(0) tensor(1) tensor(6)
tensor([2, 3, 4]) tensor([4, 5])
tensor([0, 1]) tensor([3, 4, 5, 6])


#### 2) 2D with PyTorch

In [7]:
t = torch.tensor([[i,i+1,i+2] for i in range(1,11,3)])
t

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [8]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [9]:
# 첫 번째 차원을 전체 선택,
# 두 번째 차원의 1번째만
print(t[:,1].size())

tensor([ 2,  5,  8, 11])
torch.Size([4])


In [10]:
# 첫 번째 차원을 전체 선택,
# 두 번째 차원은 맨 마지막에서 첫 번째를 제외하고 전부
t[:,:-1]

tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])

#### 3) 브로드캐스팅

자동으로 크기를 맞춰서 연산을 수행하게 한다.

In [11]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [12]:
# Vector + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) #  [3] -> [3,3]

print(m1 + m2)

tensor([[4., 5.]])


In [13]:
# 2 * 1 Vector + 1 * 2 Vector
m1 = torch.FloatTensor([[1,2]]) # 크기 (1,2)
m2 = torch.FloatTensor([[3],
                        [4]])   # 크기 (2,1)
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


#### 4) 자주 사용되는 기능

##### 1) 행렬 곱셈과 곱셈의 차이

In [8]:
m1 = torch.FloatTensor([[1,2],
                        [3,4]])
# 안쪽의 ,(쉼표)를 전환해서 생각하자.
m2 = torch.FloatTensor([[1],[2]])

print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])


행렬 곱셈

In [11]:
print(m1.matmul(m2))

tensor([[ 5.],
        [11.]])


element-wise 곱셈
    
브로드캐스팅되어서 곱해진다.

즉, 다음과 같이 변한다.  
[1]  
[2]  
==>  
[[1, 1],  
     [2, 2]]

In [10]:
print(m1 * m2) 

tensor([[1., 2.],
        [6., 8.]])


##### 2) 평균(Mean)

In [12]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [13]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [14]:
print(t.mean())

tensor(2.5000)


In [ ]:
print(t.mean(dim=0))

dim = 0은 첫 번째 차원인 행을 지정한다.   
axis = 0, 행을 기준으로 접어서 평균을 계산한다.

In [ ]:
print(t.mean(dim=0))

tensor([2., 3.])


##### 3) 덧셈(Sum)

In [19]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.shape)

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


In [18]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


##### 4) 최대(Max)와 아그맥스(ArgMax)

In [20]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [21]:
print(t.max())

tensor(4.)


In [ ]:
# Returns two values: max and argmax
# max에 dim 인자를 주면 argmax도 함께 리턴하는 특징이 있다.
print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [23]:
# dim 인자를 준 상태에서, max or argmax를 하나만 리턴 받고 싶다면, 인덱싱에서 프린트하면 된다.
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [24]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


##### 5) 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경
##### 매우 중요!

In [27]:
import numpy as np
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [28]:
print(ft.shape)

torch.Size([2, 2, 3])


##### 5-1) 3차원 텐서에서 2차원 텐서로 변경

ft.view([-1,3])에서, -1을 지정하면 사용자가 잘 모르겠으니,  파이토치에게 맡기겠다는 뜻이다.  

In [29]:
print(ft.view([-1,3])) # ft라는 텐서를 (?,3)의 크기로 변경
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


##### 6) 스퀴즈(Squeeze) -  1인 차원을 제거한다.

In [3]:
import torch
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [4]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


##### 7) 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다.

In [6]:
ft = torch.Tensor([0,1,2])
print(ft.shape) 

torch.Size([3])


In [ ]:
# 첫 번째 차원(0)에 1차원을 추가한다.
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
# 두 번째 차원에 1을 추가하겠다.
# 현재 크기는 (3,)이었으므로, 추가하면 (3,1)의 크기를 갖는다.
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [11]:
# 마지막 차원에 1을 추가하겠다.
# 현재 크기는 (3,)이었으므로, 추가하면 (3,1)의 크기를 갖는다.
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


##### 8) 타입 캐스팅(Type Casting)

Tensor의 자료형을 변환하는 것

In [14]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [15]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [16]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [17]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


##### 9) 연결하기

In [19]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [ ]:
# 0차원, 즉 행이 늘어나는 방향으로 합친다.
print(torch.cat([x,y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [21]:
print(torch.cat([x,y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


##### 10) 스택킹(stacking)

스택킹은 연결(concatenate)하는 또 다른 방법이다.

In [22]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [ ]:
#텐서의 차원도 바꿔주며, 연결한다.
print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
print(torch.stack([x,y,z], dim = 1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


##### 11) ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서

In [27]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [ ]:
# x와 동일한 크기이지만 1로만 값이 채워진 텐서
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [29]:
# x와 동일한 크기이지만 0로만 값이 채워진 텐서
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


##### 12) In-place Operation (덮어쓰기 연산)

In [30]:
x = torch.FloatTensor([[1,2],[3,4]])

In [31]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [32]:
# 곱한 결과를 덮어쓰기 하여 변수 x에 저장한다.
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
