이번에는 파이토치에서 이미 구현된 함수들을 불러와서 더 쉽게 선형 회귀 모델을 구현해본다.

### 1. 단순 선형 회귀

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
torch.manual_seed(1)

In [3]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [ ]:
# input_dim = 1, output_dim = 1
# 하나의 입력 x, 하나의 출력 y이므로, 모두 1을 넣었다.
model = nn.Linear(1,1)  

In [7]:
# model에 저장되어 있는 가중치 W와 편향 b
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]


In [9]:
# optimizer 설정. 경사하강법 SGD를 사용하고 learning rate는 0.01
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [11]:
# 전체 훈련 데이터에 대해 경사하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(np_epochs+1):
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    # pytorch에서 제공하는 평균제곱오차 함수
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    # 비용함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()    

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 14.714844
Epoch  100/2000 Cost: 0.127436
Epoch  200/2000 Cost: 0.078748
Epoch  300/2000 Cost: 0.048661
Epoch  400/2000 Cost: 0.030070
Epoch  500/2000 Cost: 0.018581
Epoch  600/2000 Cost: 0.011482
Epoch  700/2000 Cost: 0.007095
Epoch  800/2000 Cost: 0.004384
Epoch  900/2000 Cost: 0.002709
Epoch 1000/2000 Cost: 0.001674
Epoch 1100/2000 Cost: 0.001035
Epoch 1200/2000 Cost: 0.000639
Epoch 1300/2000 Cost: 0.000395
Epoch 1400/2000 Cost: 0.000244
Epoch 1500/2000 Cost: 0.000151
Epoch 1600/2000 Cost: 0.000093
Epoch 1700/2000 Cost: 0.000058
Epoch 1800/2000 Cost: 0.000036
Epoch 1900/2000 Cost: 0.000022
Epoch 2000/2000 Cost: 0.000014


In [12]:
# 임의의 입력 4 선언
new_var = torch.FloatTensor([[4.0]])

# 입력할 값 4에 대해서 예측값 y^를 리턴받아서 pred_y에 저장
pred_y = model(new_var)

print(f'훈련 후 입력이 4일 때의 예측값 : {pred_y}')

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9926]], grad_fn=<AddmmBackward0>)


W의 값이 2에 가깝고, b의 값이 0에 가까운 것을 볼 수 있다.

In [13]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9957]], requires_grad=True), Parameter containing:
tensor([0.0097], requires_grad=True)]


- H(x) 식에 입력 x로부터 예측된 y를 얻는 것을 forward 연산이라고 한다.
- 학습 전, prediction = model(x_train)은 x_train으로부터 예측값을 리턴하므로 forward연산
- 학습 후, pred_y = model(new_var)는 임의의 값 new_var로부터 예측값을 리턴하므로 forward연산

- cost.backward()는 비용 함수로부터 기울기를 구하라는 의미이며 backward 연산이다.