이후 배우게 될 실습인 소프트맥스 회귀에서는 종속 변수 y의 종류도 3개 이상이 된다.  
이러한 식이 겹겹이 누적되면 인공 신경망의 개념이 된다.

우리는 각 변수들의 연산을 벡터와 행렬 연산으로 이해할 수 있어야 한다.  
즉, 사용자가 데이터와 변수의 개수로부터 행렬의 크기, 더 나아가 텐서의 크기를 산정할 수 있어야 한다.  


## 따라서 기본적인 벡터와 행렬 연산에 대해서 다시 복습한다.

### 1. 벡터와 행렬과 텐서

벡터  
- 크기와 방향을 가진 양이다.  
- 파이썬에서 1차원 배열 또는 리스트로 표현한다.

행렬
- 행과 열을 가지는 2차원 구조이다.
- 파이썬에서 2차원 배열로 표현한다.

텐서
- 3차원 이상의 구조이다.

### 2. 텐서

In [1]:
import numpy as np

#### 1) 0차원 텐서(스칼라)

스칼라는 하나의 실수값으로 이루어진 데이터  
OD 텐서라고도 한다.

In [2]:
d = np.array(5)
print(f'텐서의 차원 : {d.ndim}')
print(f'텐서의 크기 : {d.shape}')

텐서의 차원 : 0
텐서의 크기 : ()


ndim을 출력했을 때 나오는 값을 축(axis)의 개수, 또는 텐서의 차원이라고 부른다.

#### 2) 1차원 텐서(벡터)

'벡터의 차원'과 헷갈리지 말자.

In [3]:
d = np.array([1, 2, 3, 4])
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

텐서의 차원 : 1
텐서의 크기(shape) : (4,)


#### 3) 2차원 텐서(행렬)

In [4]:
# 3행 4열의 행렬
d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

텐서의 차원 : 2
텐서의 크기(shape) : (3, 4)


#### 4) 3차원 텐서(다차원 배열)

In [5]:
d = np.array([
            [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [10, 11, 12, 13, 14]],
            [[15, 16, 17, 18, 19], [19, 20, 21, 22, 23], [23, 24, 25, 26, 27]]
            ])
print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

텐서의 차원 : 3
텐서의 크기(shape) : (2, 3, 5)


텐서의 차원 -> 깊이. []의 갯수

자연어 처리에서 특히 이 3D 텐서를 자주 보게 된다.  
시퀀스 데이터를 표현할 때 자주 사용되기 때문이다.  
이 경우 3D 텐서는 (samples, timesteps, word_dim)이 된다.  
혹은 (batch_size, timesteps, word_dim)이라고도 볼 수 있다.

#### 5) 그 이상의 텐서  

### 3. 벡터와 행렬의 연산

In [7]:
import numpy as np

#### 1) 벡터와 행렬의 덧셈과 뺄셈

In [8]:
A = np.array([8, 4, 5])
B = np.array([1, 2, 3])
print('두 벡터의 합 :',A+B)
print('두 벡터의 차 :',A-B)

두 벡터의 합 : [9 6 8]
두 벡터의 차 : [7 2 2]


In [9]:
A = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
B = np.array([[5, 6, 7, 8],[1, 2, 3, 4]])
print('두 행렬의 합 :')
print(A + B)
print('두 행렬의 차 :')
print(A - B)

두 행렬의 합 :
[[15 26 37 48]
 [51 62 73 84]]
두 행렬의 차 :
[[ 5 14 23 32]
 [49 58 67 76]]


#### 2) 벡터의 내적과 행렬의 곱셈

In [10]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print('두 벡터의 내적 :',np.dot(A, B))

두 벡터의 내적 : 32


In [11]:
A = np.array([[1, 3],[2, 4]])
B = np.array([[5, 7],[6, 8]])
print('두 행렬의 행렬곱 :')
print(np.matmul(A, B))

두 행렬의 행렬곱 :
[[23 31]
 [34 46]]


### 4. 다중 선형 회귀 행렬 연산으로 이해하기

자세한 그림은 https://wikidocs.net/217269 참조할 것.

독립 변수가 2개 이상일 때, 1개의 종속 변수를 예측하는 문제를 행렬의 연산으로 표현한다면?  
다중 선형회귀 수식이 있다면,   
이를 입력 벡터와, 가중치 벡터의 내적으로 표현할 수 있겠다.

샘플의 갯수가 많을 경우에는 행렬의 곱셈으로 표현이 가능하다.  
H(X) = XW + B

### 5. 샘플과 특성

머신 러닝에서는 데이터를 셀 수 있는 단위로 구분할 때,  
각각을 샘플이라고 부르며, 종속 변수 y를 예측하기 위한 각각의 독립 변수 x를 특성이라고 부른다.

### 6. 가중치와 편향 행렬의 크기 결정

역시 https://wikidocs.net/217269 내용 참조