## 선형 회귀 이론을 이해하고, Pytorch를 이용하여 선형 회귀 모델을 만든다.

- 데이터에 대한 이해
- 가설 수립
- 손실 계산하기
- 경사 하강법

### 1. 데이터에 대한 이해

#### 1) 훈련 데이터셋과 테스트 데이터셋

#### 2) 훈련 데이터셋의 구성

In [1]:
import torch
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

### 2. 가설 수립

### 3. 비용 함수에 대한 이해

- MSE(평균 제곱 오차) : 오차의 제곱합에 평균을 구한다.

### 4. 옵티마이저 -  경사 하강법

### 5. 파이토치로 선형 회귀 구현하기

#### 1) 기본 셋팅

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [7]:
torch.manual_seed(1)

#### 2) 변수 선언

In [8]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [9]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [10]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


#### 3) 가중치와 편향의 초기화

In [11]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시한다.
W = torch.zeros(1, requires_grad=True)
# 가중치 W를 출력
print(W)

tensor([0.], requires_grad=True)


In [12]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


#### 4) 가설 세우기

In [13]:
hypo = x_train * W + b
print(hypo)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


#### 5) 비용 함수 선언하기

In [14]:
# 앞서 배운 torch.mean으로 평균을 구한다.
cost = torch.mean((hypo - y_train)**2)  
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


#### 6) 경사 하강법 구현하기

In [15]:
optimizer = optim.SGD([W,b], lr = 0.01)

In [ ]:
# gradient를 0으로 초기화
optimizer.zero_grad()
# 비용 함수를 미분하여 gradient 계산
cost.backward()
# W와 b를 업데이트
optimizer.step()    

#### 7) 전체 코드

In [17]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1999

for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train)**2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()    

    # 100번마다 로그 출력

    if epoch % 100 == 0:
        print(f'Epoch {epoch:4d}/{nb_epochs} W: {W.item():.3f}, b: {b.item():.3f} Cost: {cost.item():.6f}')

Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

### 6. optimizer.zero_grad()가 필요한 이유

파이토치는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적시키는 특징이 있다.
따라서 optimizer.zero_grad()로 미분값을 계속 0으로 초기화시켜줘야 한다.

In [18]:
import torch

w = torch.tensor(2.0, requires_grad=True)

np_epochs = 20

for epoch in range(np_epochs + 1 ):
    z = 2*w 
    z.backward()
    print(f'수식을 w로 미분한 값: {w.grad}')

수식을 w로 미분한 값: 2.0
수식을 w로 미분한 값: 4.0
수식을 w로 미분한 값: 6.0
수식을 w로 미분한 값: 8.0
수식을 w로 미분한 값: 10.0
수식을 w로 미분한 값: 12.0
수식을 w로 미분한 값: 14.0
수식을 w로 미분한 값: 16.0
수식을 w로 미분한 값: 18.0
수식을 w로 미분한 값: 20.0
수식을 w로 미분한 값: 22.0
수식을 w로 미분한 값: 24.0
수식을 w로 미분한 값: 26.0
수식을 w로 미분한 값: 28.0
수식을 w로 미분한 값: 30.0
수식을 w로 미분한 값: 32.0
수식을 w로 미분한 값: 34.0
수식을 w로 미분한 값: 36.0
수식을 w로 미분한 값: 38.0
수식을 w로 미분한 값: 40.0
수식을 w로 미분한 값: 42.0


### 7. torch.manual_seed()를 하는 이유

시드를 같게 하면, 다른 컴퓨터에서 실행시켜도 동일한 결과를 얻을 수 있다.

In [19]:
import torch

torch.manual_seed(3)
print('랜덤 시드가 3일때')
for i in range(1,3):
    print(torch.rand(1))

랜덤 시드가 3일때
tensor([0.0043])
tensor([0.1056])


In [21]:
torch.manual_seed(5)
print('랜덤 시드가 5일때')
for i in range(1,3):
    print(torch.rand(1))

랜덤 시드가 5일때
tensor([0.8303])
tensor([0.1261])


### 8. 자동 미분(Autograd) 실습하기

In [22]:
import torch

In [23]:
w = torch.tensor(2.0, requires_grad=True)

In [24]:
y = w**2
z = 2*y + 5

In [25]:
z.backward()

In [26]:
print(f'수식을 w로 미분한 값 : {w.grad}')

수식을 w로 미분한 값 : 8.0
