## 소프트맥스 회귀의 비용 함수를 직접 구현해본다.

### 1. 소프트맥스 회귀의 비용 함수 구현

In [2]:
import torch
import torch.nn.functional as F

In [3]:
torch.manual_seed(1)

#### 1) 파이토치로 소프트맥스의 비용 함수 구현하기 (로우-레벨)

In [4]:
z = torch.FloatTensor([1,2,3])

3개의 원소의 값이 0과 1사이의 값을 가지는 벡터로 변환했음을 알 수 있다.

In [5]:
hypothesis = F.softmax(z, dim=0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [6]:
hypothesis.sum()

tensor(1.)

비용함수를 직접 구현해보자.

임의의 3 x 5 행렬 크기의 텐서를 만든다.

In [7]:
z = torch.rand(3, 5, requires_grad=True)

이제 이 텐서에 대해 소프트맥스 함수를 적용한다.  
단, 각 샘플에 대해서 소프트맥스 함수를 적용하여야 하므로,  
두 번째 차원에 대해서 소프트맥스 함수를 적용한다는 의미로 dim = 1를 전달한다.

In [8]:
hypothesis = F.softmax(z, dim=1)
print(hypothesis)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>)


이제 각 행의 원소 합이 1이 되는 텐서로 변환되었다.  
소프트맥스 함수의 출력값은 결국 예측값이다.  
즉, 3개의 샘플에 대해서, 5개의 클래스 중 어떤 클래스가 정답인지 예측한 결과이다.

이제 각 샘플에 대해서 임의의 레이블을 만든다.

In [9]:
# 첫 번째 파라미터, high, 0부터 4까지의 정수
# (3,)은 size 파라미터, 생성될 tensor의 형태를 지정

# .long()은 텐서의 데이터타입을 64비트 정수형으로 변환
y = torch.randint(5, (3,)).long()
print(y)
print(y.shape)

tensor([0, 2, 1])
torch.Size([3])


이제 각 레이블에 대해서 원-핫 인코딩을 수행한다.

In [ ]:
# 모든 원소가 0의 값을 가진 3 x 5 텐서 생성
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1), 1)

# y.shape -> torch.Size([3])
# y.unsqueeze(1).shape -> torch.Size([3, 1])
# 즉 1의 위치에, 차원을 하나 추가. 3 X 1인 2차원 텐서로 바뀜.

# 메소드_ : 덮어쓰기 연산(In-place Operation)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])